version: '3.8'

services:
  langmap:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: langmap
    ports:
      - "4173:4173"
    restart: unless-stopped
    environment:
      - NODE_ENV=production 